/**
 * Pre-assigned verified specialists across all 18 trades for the 8 primary metropolitan cities.
 * Provides authentic local specialist profiles, localities, ratings, and rates.
 */

const PRE_ASSIGNED_WORKERS = [
  // ==========================================
  // 1. KOLKATA (CCU) - 18 Trades
  // ==========================================
  {
    id: 'pro_ccu_elec_1',
    name: 'Subhashis Banerjee',
    city: 'Kolkata',
    locality: 'Salt Lake & New Town',
    skillCategory: 'Electrician & Wiring Repairs',
    specificSkill: 'MCB switches, inverter cabling & 3-phase wiring',
    experience: '7 years',
    baseRate: 349,
    rating: 4.95,
    completedJobs: 138,
    bio: 'Government-certified wireman with 7 years serving Salt Lake and Rajarhat households.'
  },
  {
    id: 'pro_ccu_plumb_1',
    name: 'Anirban Das',
    city: 'Kolkata',
    locality: 'Gariahat & Jadavpur',
    skillCategory: 'Plumbing & Drainage Fixing',
    specificSkill: 'Concealed pipe leakages & bathroom fittings',
    experience: '9 years',
    baseRate: 349,
    rating: 4.88,
    completedJobs: 142,
    bio: 'Senior plumber known for quick 30-min arrival in South Kolkata.'
  },
  {
    id: 'pro_ccu_clean_1',
    name: 'Priya Sen',
    city: 'Kolkata',
    locality: 'Park Street & Ballygunge',
    skillCategory: 'Deep Home & Kitchen Cleaning',
    specificSkill: 'Degreasing kitchens & deep sanitization',
    experience: '5 years',
    baseRate: 699,
    rating: 4.92,
    completedJobs: 215,
    bio: 'Eco-friendly deep cleaning specialist with industrial steaming equipment.'
  },
  {
    id: 'pro_ccu_carp_1',
    name: 'Ratan Mondal',
    city: 'Kolkata',
    locality: 'Dum Dum & Lake Town',
    skillCategory: 'Custom Carpentry & Woodwork',
    specificSkill: 'Modular wardrobe installation & teak wood restoration',
    experience: '11 years',
    baseRate: 499,
    rating: 4.89,
    completedJobs: 160,
    bio: 'Master craftsman specializing in modern minimalist plywood and laminate designs.'
  },
  {
    id: 'pro_ccu_handy_1',
    name: 'Bapi Samanta',
    city: 'Kolkata',
    locality: 'Behala & New Alipore',
    skillCategory: 'Furniture Assembly & Handyman',
    specificSkill: 'Wall drillings, TV mounts, curtain rods & IKEA assemblies',
    experience: '6 years',
    baseRate: 349,
    rating: 4.91,
    completedJobs: 175,
    bio: 'Equipped with laser-level drill sets and Bosch hardware fixtures.'
  },
  {
    id: 'pro_ccu_appliance_1',
    name: 'Debojyoti Ghosh',
    city: 'Kolkata',
    locality: 'Howrah & Shibpur',
    skillCategory: 'AC, Fridge & Appliance Repair',
    specificSkill: 'Split AC jet cleaning & inverter compressor fixes',
    experience: '8 years',
    baseRate: 449,
    rating: 4.90,
    completedJobs: 174,
    bio: 'Former authorized Daikin/LG service technician with genuine OEM spare parts.'
  },
  {
    id: 'pro_ccu_paint_1',
    name: 'Soumen Halder',
    city: 'Kolkata',
    locality: 'Ballygunge & Tollygunge',
    skillCategory: 'Wall Painting & Waterproofing',
    specificSkill: 'Asian Paints Royal luxury coat, damp sealing & wall putty',
    experience: '9 years',
    baseRate: 899,
    rating: 4.93,
    completedJobs: 140,
    bio: 'Dustless sanding and anti-fungal waterproofing specialist for monsoon dampness.'
  },
  {
    id: 'pro_ccu_tutor_1',
    name: 'Sharmistha Mukherjee',
    city: 'Kolkata',
    locality: 'South City & Jadavpur',
    skillCategory: 'Tutoring',
    specificSkill: 'ICSE & CBSE Class 8–12 Mathematics & Physics',
    experience: '6 years',
    baseRate: 800,
    rating: 5.0,
    completedJobs: 86,
    bio: 'M.Sc. Mathematics with verified 100% first-division student track record.'
  },
  {
    id: 'pro_ccu_spa_1',
    name: 'Tanusree Roy',
    city: 'Kolkata',
    locality: 'Alipore & Hastings',
    skillCategory: 'Spa, Massage & Grooming',
    specificSkill: 'Aromatherapy & Swedish relaxation therapy',
    experience: '6 years',
    baseRate: 1199,
    rating: 4.97,
    completedJobs: 145,
    bio: 'Certified wellness aesthetician bringing hygienic, salon-grade treatments home.'
  },
  {
    id: 'pro_ccu_tech_1',
    name: 'Biswajit Paul',
    city: 'Kolkata',
    locality: 'Sector V & New Town',
    skillCategory: 'Laptop & Wi-Fi Tech Support',
    specificSkill: 'Mac/Windows SSD upgrades, mesh Wi-Fi & data recovery',
    experience: '5 years',
    baseRate: 399,
    rating: 4.93,
    completedJobs: 128,
    bio: 'Hardware diagnostician solving complex networking and thermal throttling issues.'
  },
  {
    id: 'pro_ccu_fit_1',
    name: 'Joydeep Bhattacharya',
    city: 'Kolkata',
    locality: 'Southern Avenue & Golf Green',
    skillCategory: 'Yoga & Fitness Coaching',
    specificSkill: 'Hatha Yoga, weight loss workouts & posture alignment',
    experience: '5 years',
    baseRate: 799,
    rating: 4.96,
    completedJobs: 98,
    bio: 'Certified yoga trainer and personal fitness mentor for sedentary professionals.'
  },
  {
    id: 'pro_ccu_auto_1',
    name: 'Prabir Dutta',
    city: 'Kolkata',
    locality: 'Rajarhat & VIP Road',
    skillCategory: 'Car & Two-Wheeler Care',
    specificSkill: 'Doorstep waterless foam wash, interior shampooing & polymer polish',
    experience: '6 years',
    baseRate: 499,
    rating: 4.90,
    completedJobs: 156,
    bio: 'Mobile detailing van with eco-friendly pH-neutral shampoos and ceramic topcoats.'
  },
  {
    id: 'pro_ccu_pest_1',
    name: 'Amitava Sen',
    city: 'Kolkata',
    locality: 'Kestopur & Ultadanga',
    skillCategory: 'Pest Control & Fumigation',
    specificSkill: 'Odorless cockroach gel baiting & anti-termite drilling',
    experience: '8 years',
    baseRate: 799,
    rating: 4.88,
    completedJobs: 182,
    bio: 'Government-approved herbal pest control with 100% food-safe certifications.'
  },
  {
    id: 'pro_ccu_org_1',
    name: 'Madhumita Chakraborty',
    city: 'Kolkata',
    locality: 'Salt Lake & Kankurgachi',
    skillCategory: 'Wardrobe & Home Organisation',
    specificSkill: 'KonMari wardrobe folding, pantry storage & seasonal decluttering',
    experience: '4 years',
    baseRate: 649,
    rating: 4.94,
    completedJobs: 90,
    bio: 'Organising expert turning chaotic closets into tranquil, functional spaces.'
  },
  {
    id: 'pro_ccu_baby_1',
    name: 'Kalyani Biswas',
    city: 'Kolkata',
    locality: 'Garia & Ruby',
    skillCategory: 'Babysitting & Childcare',
    specificSkill: 'Toddler engagement, hygienic meal preparation & bedtime storytelling',
    experience: '7 years',
    baseRate: 349,
    rating: 4.95,
    completedJobs: 165,
    bio: 'First-aid trained, CPR-certified motherly caregiver trusted by busy parents.'
  },
  {
    id: 'pro_ccu_pet_1',
    name: 'Rohan Nandy',
    city: 'Kolkata',
    locality: 'Dhakuria & Jodhpur Park',
    skillCategory: 'Pet Care & Dog Walking',
    specificSkill: 'Daily energetic walks, basic leash etiquette & dog grooming',
    experience: '4 years',
    baseRate: 349,
    rating: 4.92,
    completedJobs: 120,
    bio: 'Passionate animal behaviorist providing joyful walks and attentive pet sitting.'
  },
  {
    id: 'pro_ccu_garden_1',
    name: 'Nirmal Sardar',
    city: 'Kolkata',
    locality: 'Bansdroni & Sonarpur',
    skillCategory: 'Garden & Plant Care',
    specificSkill: 'Balcony repotting, organic pest treatment & ornamental trimming',
    experience: '10 years',
    baseRate: 449,
    rating: 4.91,
    completedJobs: 140,
    bio: 'Traditional master gardener specialized in rooftop terrace gardens and bonsai care.'
  },
  {
    id: 'pro_ccu_senior_1',
    name: 'Gita Mukherjee',
    city: 'Kolkata',
    locality: 'Behala & Taratala',
    skillCategory: 'Senior Care & Assistance',
    specificSkill: 'Medication reminders, companion walks & wheelchair mobility support',
    experience: '6 years',
    baseRate: 449,
    rating: 4.98,
    completedJobs: 135,
    bio: 'Empathetic geriatric companion providing gentle, respectful care and assistance.'
  },

  // ==========================================
  // 2. BENGALURU (BLR) - 18 Trades
  // ==========================================
  {
    id: 'pro_blr_elec_1',
    name: 'Ramesh Kumar',
    city: 'Bengaluru',
    locality: 'Indiranagar & Koramangala',
    skillCategory: 'Electrician & Wiring Repairs',
    specificSkill: 'Home wiring, inverter setup & MCB installation',
    experience: '7 years',
    baseRate: 299,
    rating: 4.94,
    completedJobs: 182,
    bio: 'Top-rated Indiranagar electrical contractor with 24/7 emergency response.'
  },
  {
    id: 'pro_blr_plumb_1',
    name: 'Suresh Babu',
    city: 'Bengaluru',
    locality: 'Jayanagar & JP Nagar',
    skillCategory: 'Plumbing & Drainage Fixing',
    specificSkill: 'Geyser connections, RO water purifier fitting & sewer snaking',
    experience: '8 years',
    baseRate: 349,
    rating: 4.92,
    completedJobs: 165,
    bio: 'Reliable South Bengaluru plumber with heavy-duty diagnostic snake cameras.'
  },
  {
    id: 'pro_blr_clean_1',
    name: 'Kavitha Reddy',
    city: 'Bengaluru',
    locality: 'Whitefield & Marathahalli',
    skillCategory: 'Deep Home & Kitchen Cleaning',
    specificSkill: 'Full villa deep scrubbing & bathroom descaling',
    experience: '6 years',
    baseRate: 699,
    rating: 4.88,
    completedJobs: 195,
    bio: 'Specialist in apartment move-in cleanings and herbal sanitization.'
  },
  {
    id: 'pro_blr_carp_1',
    name: 'Venkatesh Murthy',
    city: 'Bengaluru',
    locality: 'Malleshwaram & Rajajinagar',
    skillCategory: 'Custom Carpentry & Woodwork',
    specificSkill: 'Modular kitchen cabinets, door hinges & wooden flooring',
    experience: '9 years',
    baseRate: 499,
    rating: 4.90,
    completedJobs: 150,
    bio: 'Precision craftsman with decade-long experience in high-end modular fixtures.'
  },
  {
    id: 'pro_blr_handy_1',
    name: 'Manjunath Gowda',
    city: 'Bengaluru',
    locality: 'HSR Layout & Bellandur',
    skillCategory: 'Furniture Assembly & Handyman',
    specificSkill: 'IKEA furniture assembly, TV wall mounts & curtain rods',
    experience: '5 years',
    baseRate: 349,
    rating: 4.91,
    completedJobs: 210,
    bio: 'Laser-level precision mounting and flat-pack assembly pro.'
  },
  {
    id: 'pro_blr_appliance_1',
    name: 'Pradeep Shetty',
    city: 'Bengaluru',
    locality: 'Koramangala & BTM Layout',
    skillCategory: 'AC, Fridge & Appliance Repair',
    specificSkill: 'Inverter AC repair, refrigerator thermostat & front-load washing machines',
    experience: '8 years',
    baseRate: 449,
    rating: 4.93,
    completedJobs: 180,
    bio: 'Authorised multibrand appliance engineer with genuine spare replacements.'
  },
  {
    id: 'pro_blr_paint_1',
    name: 'Gopal Krishna',
    city: 'Bengaluru',
    locality: 'Sarjapur Road & Harlur',
    skillCategory: 'Wall Painting & Waterproofing',
    specificSkill: 'Interior emulsion, texture wall painting & terrace waterproofing',
    experience: '7 years',
    baseRate: 899,
    rating: 4.91,
    completedJobs: 130,
    bio: 'Professional wall painter offering color consultation and dust-free execution.'
  },
  {
    id: 'pro_blr_tutor_1',
    name: 'Ananya Raghavan',
    city: 'Bengaluru',
    locality: 'Sadashivanagar & Hebbal',
    skillCategory: 'Tutoring',
    specificSkill: 'CBSE & IGCSE Physics, Chemistry & Higher Mathematics',
    experience: '6 years',
    baseRate: 850,
    rating: 5.0,
    completedJobs: 110,
    bio: 'Gold medalist educator simplifying complex scientific concepts.'
  },
  {
    id: 'pro_blr_spa_1',
    name: 'Lavanya S',
    city: 'Bengaluru',
    locality: 'Indiranagar & Domlur',
    skillCategory: 'Spa, Massage & Grooming',
    specificSkill: 'Balinese massage, fruit facials & salon waxing',
    experience: '6 years',
    baseRate: 1199,
    rating: 4.96,
    completedJobs: 140,
    bio: 'Experienced spa practitioner using luxury single-use kits and organic oils.'
  },
  {
    id: 'pro_blr_tech_1',
    name: 'Karthik V',
    city: 'Bengaluru',
    locality: 'Electronic City & BTM Layout',
    skillCategory: 'Laptop & Wi-Fi Tech Support',
    specificSkill: 'Dual-band Wi-Fi routing, OS reinstalls & custom desktop builds',
    experience: '4 years',
    baseRate: 399,
    rating: 4.96,
    completedJobs: 154,
    bio: 'Tech enthusiast providing doorstep IT troubleshooting for work-from-home setups.'
  },
  {
    id: 'pro_blr_fit_1',
    name: 'Deepa Hegde',
    city: 'Bengaluru',
    locality: 'Malleshwaram & Sadashivanagar',
    skillCategory: 'Yoga & Fitness Coaching',
    specificSkill: 'Hatha yoga, posture alignment & core strength',
    experience: '5 years',
    baseRate: 799,
    rating: 5.0,
    completedJobs: 92,
    bio: 'Ayush-certified yoga instructor focusing on chronic back pain and flexibility.'
  },
  {
    id: 'pro_blr_auto_1',
    name: 'Chethan Swamy',
    city: 'Bengaluru',
    locality: 'HSR Layout & Bellandur',
    skillCategory: 'Car & Two-Wheeler Care',
    specificSkill: 'High-pressure foam wash, interior deep vacuuming & windshield polish',
    experience: '5 years',
    baseRate: 499,
    rating: 4.89,
    completedJobs: 160,
    bio: 'Prompt mobile automotive detailing bringing power and water right to your driveway.'
  },
  {
    id: 'pro_blr_pest_1',
    name: 'Praveen Nair',
    city: 'Bengaluru',
    locality: 'Bannerghatta Road & Kanakapura',
    skillCategory: 'Pest Control & Fumigation',
    specificSkill: 'Bedbug heat fumigation, termite piping & mosquito misting',
    experience: '7 years',
    baseRate: 849,
    rating: 4.92,
    completedJobs: 170,
    bio: 'Eco-certified green pest exterminator safeguarding homes and pets.'
  },
  {
    id: 'pro_blr_org_1',
    name: 'Shweta Acharya',
    city: 'Bengaluru',
    locality: 'Koramangala & HSR Layout',
    skillCategory: 'Wardrobe & Home Organisation',
    specificSkill: 'Space planning, kitchen drawer zoning & walk-in closet systems',
    experience: '4 years',
    baseRate: 699,
    rating: 4.95,
    completedJobs: 85,
    bio: 'Certified professional organizer specializing in tech executive residences.'
  },
  {
    id: 'pro_blr_baby_1',
    name: 'Latha Poojari',
    city: 'Bengaluru',
    locality: 'Basavanagudi & Jayanagar',
    skillCategory: 'Babysitting & Childcare',
    specificSkill: 'Infant care, Montessori-style playtime & healthy snack preparation',
    experience: '8 years',
    baseRate: 349,
    rating: 4.97,
    completedJobs: 185,
    bio: 'Background-verified, loving nanny with extensive infant care training.'
  },
  {
    id: 'pro_blr_pet_1',
    name: 'Naveen Kumar',
    city: 'Bengaluru',
    locality: 'Whitefield & Kadugodi',
    skillCategory: 'Pet Care & Dog Walking',
    specificSkill: 'Large breed exercise routines, basic commands & puppy socialization',
    experience: '5 years',
    baseRate: 399,
    rating: 4.93,
    completedJobs: 145,
    bio: 'Certified canine handler delivering high-energy, safe urban dog walks.'
  },
  {
    id: 'pro_blr_garden_1',
    name: 'Basavarajappa M',
    city: 'Bengaluru',
    locality: 'Yelahanka & Vidyaranyapura',
    skillCategory: 'Garden & Plant Care',
    specificSkill: 'Lawn mowing, vermicompost soil mixing & drip irrigation setup',
    experience: '12 years',
    baseRate: 499,
    rating: 4.90,
    completedJobs: 165,
    bio: 'Experienced horticulturist known for flourishing balcony greens and manicured lawns.'
  },
  {
    id: 'pro_blr_senior_1',
    name: 'Sharada Bai',
    city: 'Bengaluru',
    locality: 'JP Nagar & Banashankari',
    skillCategory: 'Senior Care & Assistance',
    specificSkill: 'Elderly companionship, gentle stretching & prescription organizing',
    experience: '7 years',
    baseRate: 449,
    rating: 4.98,
    completedJobs: 140,
    bio: 'Tender and patient caregiver dedicated to promoting dignified living for elders.'
  },

  // ==========================================
  // 3. MUMBAI (BOM) - 18 Trades
  // ==========================================
  {
    id: 'pro_bom_elec_1',
    name: 'Sachin Sawant',
    city: 'Mumbai',
    locality: 'Dadar & Worli',
    skillCategory: 'Electrician & Wiring Repairs',
    specificSkill: 'Marine-grade wiring, meter boxes & switchboards',
    experience: '8 years',
    baseRate: 349,
    rating: 4.93,
    completedJobs: 172,
    bio: 'Specialist in high-rise coastal electrical protection and surge suppressors.'
  },
  {
    id: 'pro_bom_plumb_1',
    name: 'Rajesh Sharma',
    city: 'Mumbai',
    locality: 'Borivali & Kandivali',
    skillCategory: 'Plumbing & Drainage Fixing',
    specificSkill: 'High-pressure booster pumps & drain unclogging',
    experience: '7 years',
    baseRate: 399,
    rating: 4.90,
    completedJobs: 140,
    bio: 'Equipped with electric rotary drain machines for instant high-rise unclogging.'
  },
  {
    id: 'pro_bom_clean_1',
    name: 'Sneha Patil',
    city: 'Mumbai',
    locality: 'Andheri West & Juhu',
    skillCategory: 'Deep Home & Kitchen Cleaning',
    specificSkill: 'Sea-breeze damp cleaning & modular kitchen restoration',
    experience: '6 years',
    baseRate: 749,
    rating: 4.87,
    completedJobs: 185,
    bio: 'Professional cleaning crew with eco-certified disinfectants and HEPA vacuums.'
  },
  {
    id: 'pro_bom_carp_1',
    name: 'Ashok Sutar',
    city: 'Mumbai',
    locality: 'Goregaon & Malad',
    skillCategory: 'Custom Carpentry & Woodwork',
    specificSkill: 'Space-saving sliding doors, bed boxes & marine-ply cabinets',
    experience: '10 years',
    baseRate: 499,
    rating: 4.92,
    completedJobs: 175,
    bio: 'Expert in compact city apartments and customized moisture-resistant furniture.'
  },
  {
    id: 'pro_bom_handy_1',
    name: 'Santosh Jadhav',
    city: 'Mumbai',
    locality: 'Bandra & Khar',
    skillCategory: 'Furniture Assembly & Handyman',
    specificSkill: 'Curtain brackets, heavy mirror anchors & modular shelf mounting',
    experience: '6 years',
    baseRate: 399,
    rating: 4.94,
    completedJobs: 195,
    bio: 'Fast West-side handyman carrying heavy anchor bolts and precision drills.'
  },
  {
    id: 'pro_bom_appliance_1',
    name: 'Farhan Ansari',
    city: 'Mumbai',
    locality: 'Bandra & Santacruz',
    skillCategory: 'AC, Fridge & Appliance Repair',
    specificSkill: 'Inverter PCB repair, gas charging & commercial chillers',
    experience: '9 years',
    baseRate: 499,
    rating: 4.95,
    completedJobs: 230,
    bio: 'Quick 20-minute Bandra response for AC cooling drop and gas leakages.'
  },
  {
    id: 'pro_bom_paint_1',
    name: 'Kailash Gupta',
    city: 'Mumbai',
    locality: 'Chembur & Ghatkopar',
    skillCategory: 'Wall Painting & Waterproofing',
    specificSkill: 'Dr. Fixit waterproofing, anti-seepage exterior & acrylic interior paint',
    experience: '11 years',
    baseRate: 999,
    rating: 4.89,
    completedJobs: 160,
    bio: 'Proven solutions for heavy Mumbai monsoon seepage and peeling wall coats.'
  },
  {
    id: 'pro_bom_tutor_1',
    name: 'Prof. Varun Merchant',
    city: 'Mumbai',
    locality: 'South Mumbai & Colaba',
    skillCategory: 'Tutoring',
    specificSkill: 'ICSE & HSC Board Class 9–12 Pure Maths & Statistics',
    experience: '8 years',
    baseRate: 900,
    rating: 5.0,
    completedJobs: 125,
    bio: 'Top-tier academic coach turning complex algebra into simple intuitive steps.'
  },
  {
    id: 'pro_bom_spa_1',
    name: 'Rohini Deshmukh',
    city: 'Mumbai',
    locality: 'Powai & Vikhroli',
    skillCategory: 'Spa, Massage & Grooming',
    specificSkill: 'Deep tissue therapy & Ayurvedic herbal treatments',
    experience: '6 years',
    baseRate: 1299,
    rating: 5.0,
    completedJobs: 130,
    bio: 'Trained therapist bringing 5-star spa quality and disposable hygiene kits.'
  },
  {
    id: 'pro_bom_tech_1',
    name: 'Aditya More',
    city: 'Mumbai',
    locality: 'Lower Parel & Dadar',
    skillCategory: 'Laptop & Wi-Fi Tech Support',
    specificSkill: 'MacBook logic board repair, Wi-Fi 6 routers & data migration',
    experience: '5 years',
    baseRate: 449,
    rating: 4.94,
    completedJobs: 140,
    bio: 'Quick doorstep tech specialist solving complex corporate and home IT snags.'
  },
  {
    id: 'pro_bom_fit_1',
    name: 'Rohan Salunkhe',
    city: 'Mumbai',
    locality: 'Juhu & Lokhandwala',
    skillCategory: 'Yoga & Fitness Coaching',
    specificSkill: 'High-intensity interval training, calisthenics & core strengthening',
    experience: '6 years',
    baseRate: 849,
    rating: 4.97,
    completedJobs: 110,
    bio: 'Celebrity fitness trainer guiding tailored body transformations.'
  },
  {
    id: 'pro_bom_auto_1',
    name: 'Amit Kadam',
    city: 'Mumbai',
    locality: 'Thane & Mulund',
    skillCategory: 'Car & Two-Wheeler Care',
    specificSkill: 'Doorstep waterless detailing & interior steam disinfection',
    experience: '5 years',
    baseRate: 499,
    rating: 4.91,
    completedJobs: 110,
    bio: 'Mobile detailing van with pressurized steam and ceramic coating touchups.'
  },
  {
    id: 'pro_bom_pest_1',
    name: 'Deepak Shinde',
    city: 'Mumbai',
    locality: 'Navi Mumbai & Vashi',
    skillCategory: 'Pest Control & Fumigation',
    specificSkill: 'German cockroach eradication, herbal sprays & rat trapping',
    experience: '8 years',
    baseRate: 849,
    rating: 4.91,
    completedJobs: 190,
    bio: 'Certified pest exterminator for coastal apartment societies.'
  },
  {
    id: 'pro_bom_org_1',
    name: 'Pooja Vora',
    city: 'Mumbai',
    locality: 'Bandra & Khar',
    skillCategory: 'Wardrobe & Home Organisation',
    specificSkill: 'Compact apartment storage design, closet reorganization & decluttering',
    experience: '5 years',
    baseRate: 749,
    rating: 4.96,
    completedJobs: 95,
    bio: 'Interior space optimizer maximizing usable square footage in Mumbai apartments.'
  },
  {
    id: 'pro_bom_baby_1',
    name: 'Sunanda Kamble',
    city: 'Mumbai',
    locality: 'Andheri East & Powai',
    skillCategory: 'Babysitting & Childcare',
    specificSkill: 'Early childhood attention, bedtime routines & healthy feeding',
    experience: '9 years',
    baseRate: 399,
    rating: 4.94,
    completedJobs: 210,
    bio: 'Warm and thoroughly verified nanny trusted by doctors and working parents.'
  },
  {
    id: 'pro_bom_pet_1',
    name: 'Siddharth Rane',
    city: 'Mumbai',
    locality: 'Bandra West & Carter Road',
    skillCategory: 'Pet Care & Dog Walking',
    specificSkill: 'Morning & evening seaside walks, agility training & grooming bath',
    experience: '4 years',
    baseRate: 399,
    rating: 4.95,
    completedJobs: 150,
    bio: 'Passionate dog lover offering safe, energizing Carter Road promenades.'
  },
  {
    id: 'pro_bom_garden_1',
    name: 'Pandurang Mali',
    city: 'Mumbai',
    locality: 'Versova & Juhu',
    skillCategory: 'Garden & Plant Care',
    specificSkill: 'Sea-facing balcony botanicals, bougainvillea care & vertical planters',
    experience: '14 years',
    baseRate: 499,
    rating: 4.89,
    completedJobs: 175,
    bio: 'Master of coastal salinity-resistant balcony plants and organic compost.'
  },
  {
    id: 'pro_bom_senior_1',
    name: 'Vimla Tiwari',
    city: 'Mumbai',
    locality: 'Dadar & Matunga',
    skillCategory: 'Senior Care & Assistance',
    specificSkill: 'Gentle companionship, BP/sugar log maintenance & doctor escorting',
    experience: '7 years',
    baseRate: 499,
    rating: 4.97,
    completedJobs: 145,
    bio: 'Compassionate attendant specialized in patient, attentive elder support.'
  },

  // ==========================================
  // 4. DELHI (DEL) - 18 Trades
  // ==========================================
  {
    id: 'pro_del_elec_1',
    name: 'Virender Kumar',
    city: 'Delhi',
    locality: 'Rohini & Pitampura',
    skillCategory: 'Electrician & Wiring Repairs',
    specificSkill: 'Phase shifting, heavy geyser wiring & LED panel installation',
    experience: '7 years',
    baseRate: 299,
    rating: 4.88,
    completedJobs: 165,
    bio: 'Fast North Delhi electrician solving tripping MCBs and voltage fluctuations.'
  },
  {
    id: 'pro_del_plumb_1',
    name: 'Manoj Verma',
    city: 'Delhi',
    locality: 'Janakpuri & Uttam Nagar',
    skillCategory: 'Plumbing & Drainage Fixing',
    specificSkill: 'Submersible motor repair, CPVC hot water lines & leaking taps',
    experience: '8 years',
    baseRate: 349,
    rating: 4.90,
    completedJobs: 170,
    bio: 'Equipped with heavy pipe wrenches and pressure testing gauges.'
  },
  {
    id: 'pro_del_clean_1',
    name: 'Sunita Verma',
    city: 'Delhi',
    locality: 'Dwarka & Janakpuri',
    skillCategory: 'Deep Home & Kitchen Cleaning',
    specificSkill: 'Festive deep cleaning, chimney & bathroom scrub',
    experience: '6 years',
    baseRate: 699,
    rating: 4.91,
    completedJobs: 180,
    bio: 'Thorough West Delhi home care with 100% satisfaction guarantee.'
  },
  {
    id: 'pro_del_carp_1',
    name: 'Gurpreet Singh',
    city: 'Delhi',
    locality: 'Tilak Nagar & Rajouri Garden',
    skillCategory: 'Custom Carpentry & Woodwork',
    specificSkill: 'Sheesham wood restoration, bed repairs & hydraulic hinges',
    experience: '10 years',
    baseRate: 499,
    rating: 4.93,
    completedJobs: 155,
    bio: 'Veteran carpenter delivering robust wooden furnishings and smooth fittings.'
  },
  {
    id: 'pro_del_handy_1',
    name: 'Harpreet Singh',
    city: 'Delhi',
    locality: 'Lajpat Nagar & South Extension',
    skillCategory: 'Furniture Assembly & Handyman',
    specificSkill: 'Heavy furniture assembly, door locks & drywall fixing',
    experience: '8 years',
    baseRate: 399,
    rating: 4.94,
    completedJobs: 190,
    bio: 'Friendly South Delhi handyman equipped with all heavy-duty Bosch power tools.'
  },
  {
    id: 'pro_del_appliance_1',
    name: 'Mohd. Tariq',
    city: 'Delhi',
    locality: 'Mayur Vihar & Noida',
    skillCategory: 'AC, Fridge & Appliance Repair',
    specificSkill: 'Inverter AC repair, gas charging & double-door fridge repair',
    experience: '10 years',
    baseRate: 449,
    rating: 4.95,
    completedJobs: 215,
    bio: 'Master HVAC pro with 10 years experience across East Delhi & NCR.'
  },
  {
    id: 'pro_del_paint_1',
    name: 'Jagdish Chander',
    city: 'Delhi',
    locality: 'Connaught Place & Karol Bagh',
    skillCategory: 'Wall Painting & Waterproofing',
    specificSkill: 'Asian Paints Royal luxury finish & terrace damp sealing',
    experience: '12 years',
    baseRate: 999,
    rating: 4.92,
    completedJobs: 135,
    bio: 'Precision spray painter with dust-free sanding machines.'
  },
  {
    id: 'pro_del_tutor_1',
    name: 'Dr. Nidhi Bansal',
    city: 'Delhi',
    locality: 'Hauz Khas & Vasant Kunj',
    skillCategory: 'Tutoring',
    specificSkill: 'CBSE Class 9–12 Physics & Advanced Calculus',
    experience: '6 years',
    baseRate: 900,
    rating: 5.0,
    completedJobs: 104,
    bio: 'PhD scholar offering conceptual STEM clarity and personalized worksheets.'
  },
  {
    id: 'pro_del_spa_1',
    name: 'Geeta Rawat',
    city: 'Delhi',
    locality: 'Saket & Malviya Nagar',
    skillCategory: 'Spa, Massage & Grooming',
    specificSkill: 'Ayurvedic Potli massage, bridal facials & body polishing',
    experience: '7 years',
    baseRate: 1199,
    rating: 4.95,
    completedJobs: 160,
    bio: 'Certified wellness therapist bringing calming luxury spa sessions to your doorstep.'
  },
  {
    id: 'pro_del_tech_1',
    name: 'Sahil Gulati',
    city: 'Delhi',
    locality: 'Nehru Place & Kalkaji',
    skillCategory: 'Laptop & Wi-Fi Tech Support',
    specificSkill: 'Motherboard soldering, thermal cooling paste & Wi-Fi mesh systems',
    experience: '6 years',
    baseRate: 399,
    rating: 4.96,
    completedJobs: 175,
    bio: 'Nehru Place trained chip-level laptop and networking specialist.'
  },
  {
    id: 'pro_del_fit_1',
    name: 'Vikram Bhati',
    city: 'Delhi',
    locality: 'Greater Kailash & CR Park',
    skillCategory: 'Yoga & Fitness Coaching',
    specificSkill: 'Functional mobility, Ashtanga yoga & fat-burn training',
    experience: '5 years',
    baseRate: 799,
    rating: 4.94,
    completedJobs: 105,
    bio: 'Dedicated personal trainer helping clients achieve sustainable fitness goals.'
  },
  {
    id: 'pro_del_auto_1',
    name: 'Kuldeep Yadav',
    city: 'Delhi',
    locality: 'Paschim Vihar & Punjabi Bagh',
    skillCategory: 'Car & Two-Wheeler Care',
    specificSkill: 'Doorstep pressurized foam wash & Teflon paint protection coating',
    experience: '6 years',
    baseRate: 499,
    rating: 4.90,
    completedJobs: 140,
    bio: 'Car care enthusiast delivering spotless showroom shine directly to your home.'
  },
  {
    id: 'pro_del_pest_1',
    name: 'Ravinder Negi',
    city: 'Delhi',
    locality: 'Laxmi Nagar & Preet Vihar',
    skillCategory: 'Pest Control & Fumigation',
    specificSkill: 'Termite soil treatment, herbal cockroach paste & mosquito thermal fogging',
    experience: '9 years',
    baseRate: 799,
    rating: 4.89,
    completedJobs: 195,
    bio: 'Licensed pest control specialist with safe odorless solutions.'
  },
  {
    id: 'pro_del_org_1',
    name: 'Ritu Aggarwal',
    city: 'Delhi',
    locality: 'Civil Lines & Model Town',
    skillCategory: 'Wardrobe & Home Organisation',
    specificSkill: 'Winter clothing preservation, luxury wardrobe styling & kitchen zoning',
    experience: '4 years',
    baseRate: 699,
    rating: 4.93,
    completedJobs: 80,
    bio: 'Professional organizer creating orderly, beautiful, and sustainable living spaces.'
  },
  {
    id: 'pro_del_baby_1',
    name: 'Meena Devi',
    city: 'Delhi',
    locality: 'Patel Nagar & Karol Bagh',
    skillCategory: 'Babysitting & Childcare',
    specificSkill: 'Infant massage, hygienic feeding & interactive play engagement',
    experience: '10 years',
    baseRate: 349,
    rating: 4.96,
    completedJobs: 230,
    bio: 'Highly experienced and deeply nurturing nanny with verified credentials.'
  },
  {
    id: 'pro_del_pet_1',
    name: 'Amanpreet Sethi',
    city: 'Delhi',
    locality: 'Defence Colony & Lajpat Nagar',
    skillCategory: 'Pet Care & Dog Walking',
    specificSkill: 'Structured park walks, behavioral reinforcement & pet bathing',
    experience: '4 years',
    baseRate: 399,
    rating: 4.92,
    completedJobs: 130,
    bio: 'Compassionate animal lover providing reliable care and joyful exercise for dogs.'
  },
  {
    id: 'pro_del_garden_1',
    name: 'Ramphal Saini',
    city: 'Delhi',
    locality: 'Vasant Vihar & Chanakyapuri',
    skillCategory: 'Garden & Plant Care',
    specificSkill: 'Air-purifying indoor plants, seasonal flowering & lawn hedge sculpting',
    experience: '15 years',
    baseRate: 499,
    rating: 4.93,
    completedJobs: 210,
    bio: 'Expert Delhi gardener experienced in Delhi climate landscaping and potted plants.'
  },
  {
    id: 'pro_del_senior_1',
    name: 'Sushila Kaushik',
    city: 'Delhi',
    locality: 'Rohini & Shalimar Bagh',
    skillCategory: 'Senior Care & Assistance',
    specificSkill: 'Mobility support, daily reading companionship & medicine scheduling',
    experience: '8 years',
    baseRate: 449,
    rating: 4.98,
    completedJobs: 160,
    bio: 'Dedicated elderly companion ensuring comfort, safety, and cheerfulness.'
  },

  // ==========================================
  // 5. CHENNAI (MAA) - 18 Trades
  // ==========================================
  {
    id: 'pro_maa_elec_1',
    name: 'Murugan Natarajan',
    city: 'Chennai',
    locality: 'T. Nagar & Mylapore',
    skillCategory: 'Electrician & Wiring Repairs',
    specificSkill: 'Inverter battery setup & 3-phase wiring',
    experience: '9 years',
    baseRate: 299,
    rating: 4.95,
    completedJobs: 188,
    bio: 'Licensed electrician with 9 years of trusted service in Central Chennai.'
  },
  {
    id: 'pro_maa_plumb_1',
    name: 'K. Saravanan',
    city: 'Chennai',
    locality: 'Anna Nagar & Kilpauk',
    skillCategory: 'Plumbing & Drainage Fixing',
    specificSkill: 'Overhead sump tank automation & PVC pipeline fittings',
    experience: '7 years',
    baseRate: 349,
    rating: 4.89,
    completedJobs: 145,
    bio: 'Specialist in sensor float valves, water motor repairs, and tap fittings.'
  },
  {
    id: 'pro_maa_clean_1',
    name: 'K. Vasanthi',
    city: 'Chennai',
    locality: 'Velachery & Adyar',
    skillCategory: 'Deep Home & Kitchen Cleaning',
    specificSkill: 'High-humidity mold removal & deep kitchen tile scrub',
    experience: '6 years',
    baseRate: 649,
    rating: 4.90,
    completedJobs: 175,
    bio: 'Dedicated cleaning pro tackling coastal salt residue and grime.'
  },
  {
    id: 'pro_maa_carp_1',
    name: 'R. Senthil Kumar',
    city: 'Chennai',
    locality: 'Mylapore & Alwarpet',
    skillCategory: 'Custom Carpentry & Woodwork',
    specificSkill: 'Teak pooja mandapam crafting, wooden door locks & wardrobe repair',
    experience: '12 years',
    baseRate: 499,
    rating: 4.92,
    completedJobs: 160,
    bio: 'Master woodworker creating fine traditional and contemporary furniture.'
  },
  {
    id: 'pro_maa_handy_1',
    name: 'M. Jayavel',
    city: 'Chennai',
    locality: 'Nungambakkam & Kodambakkam',
    skillCategory: 'Furniture Assembly & Handyman',
    specificSkill: 'Wall mount TVs, mosquito net frames & curtain rod fittings',
    experience: '5 years',
    baseRate: 349,
    rating: 4.91,
    completedJobs: 180,
    bio: 'Prompt and courteous handyman equipped with all modern power tools.'
  },
  {
    id: 'pro_maa_appliance_1',
    name: 'R. Balaji',
    city: 'Chennai',
    locality: 'Velachery & OMR',
    skillCategory: 'AC, Fridge & Appliance Repair',
    specificSkill: 'High-humidity anti-rust AC coating & front-load washer fixes',
    experience: '8 years',
    baseRate: 399,
    rating: 4.94,
    completedJobs: 198,
    bio: 'Anti-corrosion specialist tackling coastal coil leaks and sensor boards.'
  },
  {
    id: 'pro_maa_paint_1',
    name: 'G. Arumugam',
    city: 'Chennai',
    locality: 'Guindy & Saidapet',
    skillCategory: 'Wall Painting & Waterproofing',
    specificSkill: 'Coastal weather-shield exterior paint & interior silk finish',
    experience: '10 years',
    baseRate: 899,
    rating: 4.89,
    completedJobs: 140,
    bio: 'Expert in sun-resistant and salt-resistant protective wall coatings.'
  },
  {
    id: 'pro_maa_tutor_1',
    name: 'Revathi Sundaram',
    city: 'Chennai',
    locality: 'Nungambakkam & T. Nagar',
    skillCategory: 'Tutoring',
    specificSkill: 'CBSE & Samacheer Kalvi Maths for Class 8–12',
    experience: '6 years',
    baseRate: 800,
    rating: 5.0,
    completedJobs: 82,
    bio: 'Patient mentor making advanced trigonometry and algebra intuitive.'
  },
  {
    id: 'pro_maa_spa_1',
    name: 'K. Jayanthi',
    city: 'Chennai',
    locality: 'Besant Nagar & Thiruvanmiyur',
    skillCategory: 'Spa, Massage & Grooming',
    specificSkill: 'Traditional herbal head massage, pedicures & skin hydration',
    experience: '6 years',
    baseRate: 1099,
    rating: 4.96,
    completedJobs: 120,
    bio: 'Holistic wellness professional bringing authentic, relaxing home spa sessions.'
  },
  {
    id: 'pro_maa_tech_1',
    name: 'Dinesh Karthik',
    city: 'Chennai',
    locality: 'OMR & Perungudi',
    skillCategory: 'Laptop & Wi-Fi Tech Support',
    specificSkill: 'IT hallway mesh setup, Linux/Windows formatting & laptop screen repair',
    experience: '5 years',
    baseRate: 399,
    rating: 4.94,
    completedJobs: 145,
    bio: 'OMR tech corridor specialist resolving hardware and Wi-Fi snags instantly.'
  },
  {
    id: 'pro_maa_fit_1',
    name: 'S. Ramkumar',
    city: 'Chennai',
    locality: 'Adyar & Besant Nagar',
    skillCategory: 'Yoga & Fitness Coaching',
    specificSkill: 'Pranayama breathing techniques, Vinyasa flow & beach fitness',
    experience: '7 years',
    baseRate: 749,
    rating: 4.97,
    completedJobs: 95,
    bio: 'Dedicated yoga acharya with focus on holistic vitality and stress relief.'
  },
  {
    id: 'pro_maa_auto_1',
    name: 'T. Manikandan',
    city: 'Chennai',
    locality: 'Anna Nagar & Mogappair',
    skillCategory: 'Car & Two-Wheeler Care',
    specificSkill: 'Doorstep foam wash, underbody anti-rust coat & microfiber buffing',
    experience: '5 years',
    baseRate: 449,
    rating: 4.91,
    completedJobs: 155,
    bio: 'Automotive care pro preventing coastal rust and delivering deep gloss finish.'
  },
  {
    id: 'pro_maa_pest_1',
    name: 'E. Venkatesan',
    city: 'Chennai',
    locality: 'Porur & Vadapalani',
    skillCategory: 'Pest Control & Fumigation',
    specificSkill: 'Subterranean termite control & herbal cockroach treatment',
    experience: '8 years',
    baseRate: 799,
    rating: 4.88,
    completedJobs: 165,
    bio: 'Guaranteed pest barrier solutions for independent homes and apartments.'
  },
  {
    id: 'pro_maa_org_1',
    name: 'S. Meenakshi',
    city: 'Chennai',
    locality: 'Adyar & Besant Nagar',
    skillCategory: 'Wardrobe & Home Organisation',
    specificSkill: 'Minimalist kitchen layout & closet compartmentalization',
    experience: '5 years',
    baseRate: 699,
    rating: 4.93,
    completedJobs: 152,
    bio: 'Transforming chaotic wardrobes and kitchen pantries into serene order.'
  },
  {
    id: 'pro_maa_baby_1',
    name: 'M. Gomathi',
    city: 'Chennai',
    locality: 'Mylapore & Mandaveli',
    skillCategory: 'Babysitting & Childcare',
    specificSkill: 'Infant bathing, wholesome porridge feeding & attentive supervision',
    experience: '8 years',
    baseRate: 349,
    rating: 4.96,
    completedJobs: 190,
    bio: 'Gentle, experienced nanny providing trustworthy and attentive child support.'
  },
  {
    id: 'pro_maa_pet_1',
    name: 'V. Prakash',
    city: 'Chennai',
    locality: 'ECR & Thiruvanmiyur',
    skillCategory: 'Pet Care & Dog Walking',
    specificSkill: 'ECR beach dog runs, tick treatment baths & positive reinforcement',
    experience: '4 years',
    baseRate: 349,
    rating: 4.93,
    completedJobs: 115,
    bio: 'Reliable pet caretaker passionate about canine health and activity.'
  },
  {
    id: 'pro_maa_garden_1',
    name: 'K. Munuswamy',
    city: 'Chennai',
    locality: 'Kotturpuram & RA Puram',
    skillCategory: 'Garden & Plant Care',
    specificSkill: 'Tropical flowering plants, neem pesticide spraying & soil mulching',
    experience: '13 years',
    baseRate: 449,
    rating: 4.91,
    completedJobs: 180,
    bio: 'Expert in tropical urban gardens, jasmine cultivation, and terrace potting.'
  },
  {
    id: 'pro_maa_senior_1',
    name: 'Lakshmi Narayanan',
    city: 'Chennai',
    locality: 'T. Nagar & West Mambalam',
    skillCategory: 'Senior Care & Assistance',
    specificSkill: 'Temple visits escort, medication reminders & compassionate conversation',
    experience: '6 years',
    baseRate: 449,
    rating: 4.98,
    completedJobs: 150,
    bio: 'Warm-hearted senior caregiver treating every elder with respect and patience.'
  },

  // ==========================================
  // 6. HYDERABAD (HYD) - 18 Trades
  // ==========================================
  {
    id: 'pro_hyd_elec_1',
    name: 'Venkat Rao',
    city: 'Hyderabad',
    locality: 'Gachibowli & Madhapur',
    skillCategory: 'Electrician & Wiring Repairs',
    specificSkill: 'Smart home automation, UPS inverter installation',
    experience: '7 years',
    baseRate: 299,
    rating: 4.93,
    completedJobs: 168,
    bio: 'Trusted Hitec City technician for high-rise apartments and villa communities.'
  },
  {
    id: 'pro_hyd_plumb_1',
    name: 'Syed Khaleel',
    city: 'Hyderabad',
    locality: 'Banjara Hills & Jubilee Hills',
    skillCategory: 'Plumbing & Drainage Fixing',
    specificSkill: 'Concealed shower valves, pressure pumps & CP fittings',
    experience: '8 years',
    baseRate: 349,
    rating: 4.94,
    completedJobs: 180,
    bio: 'Luxury bathroom fittings and zero-breakage leak detection pro.'
  },
  {
    id: 'pro_hyd_clean_1',
    name: 'Fatima Begum',
    city: 'Hyderabad',
    locality: 'Kondapur & Hitec City',
    skillCategory: 'Deep Home & Kitchen Cleaning',
    specificSkill: 'Floor buffing, tile grouting cleaning & deep dusting',
    experience: '5 years',
    baseRate: 699,
    rating: 4.88,
    completedJobs: 156,
    bio: 'Professional team specializing in tech corridor gated communities.'
  },
  {
    id: 'pro_hyd_carp_1',
    name: 'Mohd. Osman',
    city: 'Hyderabad',
    locality: 'Mehdipatnam & Tolichowki',
    skillCategory: 'Custom Carpentry & Woodwork',
    specificSkill: 'Custom TV units, hydraulic bed fittings & wood polishing',
    experience: '9 years',
    baseRate: 499,
    rating: 4.91,
    completedJobs: 145,
    bio: 'Skilled Hyderabad carpenter specializing in fine wood finishes and fittings.'
  },
  {
    id: 'pro_hyd_handy_1',
    name: 'K. Srinivas',
    city: 'Hyderabad',
    locality: 'Kukatpally & Miyapur',
    skillCategory: 'Furniture Assembly & Handyman',
    specificSkill: 'IKEA assemblies, wall shelving & ceiling fan hook installation',
    experience: '6 years',
    baseRate: 349,
    rating: 4.92,
    completedJobs: 170,
    bio: 'Experienced handyman ensuring safe, sturdy drill anchors and assemblies.'
  },
  {
    id: 'pro_hyd_appliance_1',
    name: 'Srinivasulu Reddy',
    city: 'Hyderabad',
    locality: 'Kukatpally & Miyapur',
    skillCategory: 'AC, Fridge & Appliance Repair',
    specificSkill: 'Split AC indoor/outdoor jet wash & inverter fridge repair',
    experience: '7 years',
    baseRate: 449,
    rating: 4.92,
    completedJobs: 190,
    bio: 'Certified technician with genuine copper piping and 90-day warranty.'
  },
  {
    id: 'pro_hyd_paint_1',
    name: 'Ch. Nageswara Rao',
    city: 'Hyderabad',
    locality: 'Dilsukhnagar & LB Nagar',
    skillCategory: 'Wall Painting & Waterproofing',
    specificSkill: 'Stenciled texture walls, royal sheen paint & roof heat-reflect coat',
    experience: '10 years',
    baseRate: 899,
    rating: 4.90,
    completedJobs: 135,
    bio: 'Specialist in heat-reflective terrace coatings and aesthetic interior paints.'
  },
  {
    id: 'pro_hyd_tutor_1',
    name: 'Dr. P. Sandhya',
    city: 'Hyderabad',
    locality: 'Begumpet & Somajiguda',
    skillCategory: 'Tutoring',
    specificSkill: 'IIT Foundation & CBSE Class 8–12 Mathematics',
    experience: '7 years',
    baseRate: 850,
    rating: 5.0,
    completedJobs: 95,
    bio: 'Expert educator helping students master problem-solving strategies.'
  },
  {
    id: 'pro_hyd_spa_1',
    name: 'Shabana Parveen',
    city: 'Hyderabad',
    locality: 'Jubilee Hills & Banjara Hills',
    skillCategory: 'Spa, Massage & Grooming',
    specificSkill: 'Hot stone therapy, Moroccan body polish & salon hair spas',
    experience: '6 years',
    baseRate: 1199,
    rating: 4.97,
    completedJobs: 130,
    bio: 'Luxury home spa aesthetician providing soothing rejuvenation treatments.'
  },
  {
    id: 'pro_hyd_tech_1',
    name: 'Prashanth Kumar',
    city: 'Hyderabad',
    locality: 'Secunderabad & Begumpet',
    skillCategory: 'Laptop & Wi-Fi Tech Support',
    specificSkill: 'Gaming PC builds, thermal repasting & router bridging',
    experience: '5 years',
    baseRate: 399,
    rating: 5.0,
    completedJobs: 122,
    bio: 'Fast doorstep turnaround for all hardware and software diagnostics.'
  },
  {
    id: 'pro_hyd_fit_1',
    name: 'Md. Imran',
    city: 'Hyderabad',
    locality: 'Gachibowli & Manikonda',
    skillCategory: 'Yoga & Fitness Coaching',
    specificSkill: 'CrossFit routines, endurance coaching & yoga stretching',
    experience: '5 years',
    baseRate: 799,
    rating: 4.95,
    completedJobs: 100,
    bio: 'Energetic fitness mentor designing effective personalized workout programs.'
  },
  {
    id: 'pro_hyd_auto_1',
    name: 'V. Krishna Murthy',
    city: 'Hyderabad',
    locality: 'Madhapur & Kondapur',
    skillCategory: 'Car & Two-Wheeler Care',
    specificSkill: 'Doorstep high-gloss wax, interior enzyme cleaning & engine bay wash',
    experience: '6 years',
    baseRate: 499,
    rating: 4.90,
    completedJobs: 145,
    bio: 'Automotive detailer focused on pristine clean interiors and paint clarity.'
  },
  {
    id: 'pro_hyd_pest_1',
    name: 'K. Balakrishna',
    city: 'Hyderabad',
    locality: 'Uppal & Tarnaka',
    skillCategory: 'Pest Control & Fumigation',
    specificSkill: 'Pest eradication, anti-termite wood injections & cockroach traps',
    experience: '8 years',
    baseRate: 799,
    rating: 4.89,
    completedJobs: 160,
    bio: 'Reliable pest management with non-toxic, government-approved chemicals.'
  },
  {
    id: 'pro_hyd_org_1',
    name: 'A. Vasundhara',
    city: 'Hyderabad',
    locality: 'Banjara Hills & Jubilee Hills',
    skillCategory: 'Wardrobe & Home Organisation',
    specificSkill: 'Couture wardrobe storage, kitchen pantry categorization & linen sorting',
    experience: '4 years',
    baseRate: 699,
    rating: 4.94,
    completedJobs: 85,
    bio: 'Experienced organizer delivering bespoke clutter-free organizational systems.'
  },
  {
    id: 'pro_hyd_baby_1',
    name: 'B. Anuradha',
    city: 'Hyderabad',
    locality: 'Kukatpally & Nizampet',
    skillCategory: 'Babysitting & Childcare',
    specificSkill: 'Toddler learning games, safe feeding & sleep schedule management',
    experience: '7 years',
    baseRate: 349,
    rating: 4.95,
    completedJobs: 175,
    bio: 'Trustworthy and affectionate nanny trusted by working tech families.'
  },
  {
    id: 'pro_hyd_pet_1',
    name: 'D. Sandeep',
    city: 'Hyderabad',
    locality: 'Gachibowli & Nanakramguda',
    skillCategory: 'Pet Care & Dog Walking',
    specificSkill: 'Energetic pack walks, leash manners & pet companionship',
    experience: '4 years',
    baseRate: 349,
    rating: 4.92,
    completedJobs: 110,
    bio: 'Gentle canine trainer offering joyful, reliable neighborhood dog walks.'
  },
  {
    id: 'pro_hyd_garden_1',
    name: 'Yadaiah Goud',
    city: 'Hyderabad',
    locality: 'Sainikpuri & Yapral',
    skillCategory: 'Garden & Plant Care',
    specificSkill: 'Drip system installation, lawn grass laying & organic fertilizer application',
    experience: '11 years',
    baseRate: 449,
    rating: 4.90,
    completedJobs: 150,
    bio: 'Experienced green thumb maintaining lush villa lawns and vibrant container plants.'
  },
  {
    id: 'pro_hyd_senior_1',
    name: 'T. Subbalakshmi',
    city: 'Hyderabad',
    locality: 'Vidyanagar & Shivam Road',
    skillCategory: 'Senior Care & Assistance',
    specificSkill: 'Daily elder companionship, pill dispenser organizing & mobility support',
    experience: '6 years',
    baseRate: 449,
    rating: 4.97,
    completedJobs: 130,
    bio: 'Dedicated senior companion committed to patient, warm, and attentive care.'
  },

  // ==========================================
  // 7. AHMEDABAD (AMD) - 18 Trades
  // ==========================================
  {
    id: 'pro_amd_elec_1',
    name: 'Bhavesh Patel',
    city: 'Ahmedabad',
    locality: 'Navrangpura & Satellite',
    skillCategory: 'Electrician & Wiring Repairs',
    specificSkill: 'Single & three-phase wiring, LED fixtures & inverter maintenance',
    experience: '7 years',
    baseRate: 299,
    rating: 4.92,
    completedJobs: 150,
    bio: 'Punctual Navrangpura electrician with over 150 verified West Ahmedabad visits.'
  },
  {
    id: 'pro_amd_plumb_1',
    name: 'Jignesh Shah',
    city: 'Ahmedabad',
    locality: 'Bodakdev & Thaltej',
    skillCategory: 'Plumbing & Drainage Fixing',
    specificSkill: 'Tap leak repair, pipeline replacement & water tank cleaning',
    experience: '6 years',
    baseRate: 349,
    rating: 4.88,
    completedJobs: 135,
    bio: 'Equipped with pressure jetters for spotless underground drainage lines.'
  },
  {
    id: 'pro_amd_clean_1',
    name: 'Hina Prajapati',
    city: 'Ahmedabad',
    locality: 'Vastrapur & Prahlad Nagar',
    skillCategory: 'Deep Home & Kitchen Cleaning',
    specificSkill: 'Kitchen oil stain removal & window glass sparkle cleaning',
    experience: '5 years',
    baseRate: 649,
    rating: 4.93,
    completedJobs: 168,
    bio: 'Detailed cleaning with hospital-grade sanitizers and non-toxic formulas.'
  },
  {
    id: 'pro_amd_carp_1',
    name: 'Dharmesh Suthar',
    city: 'Ahmedabad',
    locality: 'Maninagar & Paldi',
    skillCategory: 'Custom Carpentry & Woodwork',
    specificSkill: 'Modular kitchen woodwork, door locks & wooden storage boxes',
    experience: '10 years',
    baseRate: 449,
    rating: 4.91,
    completedJobs: 140,
    bio: 'Skilled traditional Suthar craftsman delivering neat wooden assemblies.'
  },
  {
    id: 'pro_amd_handy_1',
    name: 'Pankaj Vaghela',
    city: 'Ahmedabad',
    locality: 'Satellite & Jodhpur',
    skillCategory: 'Furniture Assembly & Handyman',
    specificSkill: 'Curtain rod fixing, wall drillings, TV wall mounts & minor repairs',
    experience: '5 years',
    baseRate: 349,
    rating: 4.90,
    completedJobs: 160,
    bio: 'Reliable local handyman carrying precision masonry drill bits and anchors.'
  },
  {
    id: 'pro_amd_appliance_1',
    name: 'Chirag Dave',
    city: 'Ahmedabad',
    locality: 'Maninagar & Paldi',
    skillCategory: 'AC, Fridge & Appliance Repair',
    specificSkill: 'AC summer gas top-up & washing machine drum repair',
    experience: '8 years',
    baseRate: 399,
    rating: 4.94,
    completedJobs: 182,
    bio: 'Prompt Maninagar appliance doctor offering same-day visit guarantees.'
  },
  {
    id: 'pro_amd_paint_1',
    name: 'Paresh Rawal',
    city: 'Ahmedabad',
    locality: 'Bopal & South Bopal',
    skillCategory: 'Wall Painting & Waterproofing',
    specificSkill: 'Heat-reflective terrace coatings & dust-free interior painting',
    experience: '9 years',
    baseRate: 849,
    rating: 4.90,
    completedJobs: 125,
    bio: 'Cool-roof coating specialist and quality interior paint contractor.'
  },
  {
    id: 'pro_amd_tutor_1',
    name: 'Prof. Manish Mehta',
    city: 'Ahmedabad',
    locality: 'Navrangpura & University Area',
    skillCategory: 'Tutoring',
    specificSkill: 'GSEB & CBSE Class 8–12 Maths & Science',
    experience: '7 years',
    baseRate: 750,
    rating: 4.98,
    completedJobs: 90,
    bio: 'Experienced educator providing thorough conceptual groundwork.'
  },
  {
    id: 'pro_amd_spa_1',
    name: 'Bijal Joshi',
    city: 'Ahmedabad',
    locality: 'Bodakdev & Vastrapur',
    skillCategory: 'Spa, Massage & Grooming',
    specificSkill: 'Ayurvedic head massage, herbal facial therapies & waxing',
    experience: '6 years',
    baseRate: 1099,
    rating: 4.95,
    completedJobs: 115,
    bio: 'Certified aesthetician delivering sterile, high-comfort parlor care at home.'
  },
  {
    id: 'pro_amd_tech_1',
    name: 'Hardik Panchal',
    city: 'Ahmedabad',
    locality: 'SG Highway & Gota',
    skillCategory: 'Laptop & Wi-Fi Tech Support',
    specificSkill: 'Wi-Fi mesh extender setup, Windows OS repair & RAM/SSD boosts',
    experience: '4 years',
    baseRate: 399,
    rating: 4.93,
    completedJobs: 130,
    bio: 'Doorstep computer troubleshooter for fast work-from-home resolutions.'
  },
  {
    id: 'pro_amd_fit_1',
    name: 'Mehul Desai',
    city: 'Ahmedabad',
    locality: 'Prahlad Nagar & Satellite',
    skillCategory: 'Yoga & Fitness Coaching',
    specificSkill: 'Traditional yoga asanas, breathing exercises & weight management',
    experience: '5 years',
    baseRate: 749,
    rating: 4.94,
    completedJobs: 85,
    bio: 'Certified yoga instructor dedicated to holistic mind-body wellness.'
  },
  {
    id: 'pro_amd_auto_1',
    name: 'Alpesh Parmar',
    city: 'Ahmedabad',
    locality: 'Chandkheda & Motera',
    skillCategory: 'Car & Two-Wheeler Care',
    specificSkill: 'Doorstep foam wash, windshield cleaning & interior detailing',
    experience: '5 years',
    baseRate: 449,
    rating: 4.89,
    completedJobs: 135,
    bio: 'Equipped with waterless and foam washing units for rapid car care.'
  },
  {
    id: 'pro_amd_pest_1',
    name: 'Nitin Solanki',
    city: 'Ahmedabad',
    locality: 'Naroda & Bapunagar',
    skillCategory: 'Pest Control & Fumigation',
    specificSkill: 'Termite barrier protection & odorless cockroach gel application',
    experience: '7 years',
    baseRate: 749,
    rating: 4.88,
    completedJobs: 150,
    bio: 'Safe and effective pest management for residential bungalows and flats.'
  },
  {
    id: 'pro_amd_org_1',
    name: 'Krupali Trivedi',
    city: 'Ahmedabad',
    locality: 'Satellite & Ambawadi',
    skillCategory: 'Wardrobe & Home Organisation',
    specificSkill: 'Traditional saree and wardrobe folding, kitchen pantry reorganization',
    experience: '4 years',
    baseRate: 649,
    rating: 4.92,
    completedJobs: 75,
    bio: 'Passionate organizer creating serene, well-categorized household systems.'
  },
  {
    id: 'pro_amd_baby_1',
    name: 'Geeta Vankar',
    city: 'Ahmedabad',
    locality: 'Sabarmati & Ranip',
    skillCategory: 'Babysitting & Childcare',
    specificSkill: 'Baby care, gentle playtime activities & nutritious food feeding',
    experience: '8 years',
    baseRate: 349,
    rating: 4.95,
    completedJobs: 160,
    bio: 'Patient and trustworthy nanny with extensive experience with infants and toddlers.'
  },
  {
    id: 'pro_amd_pet_1',
    name: 'Sanjay Makwana',
    city: 'Ahmedabad',
    locality: 'Vastrapur & Gurukul',
    skillCategory: 'Pet Care & Dog Walking',
    specificSkill: 'Morning lake walks, leash control & affectionate pet companionship',
    experience: '4 years',
    baseRate: 349,
    rating: 4.91,
    completedJobs: 105,
    bio: 'Reliable and friendly dog walker providing attentive care and exercise.'
  },
  {
    id: 'pro_amd_garden_1',
    name: 'Gordhanbhai Mali',
    city: 'Ahmedabad',
    locality: 'Shahibaug & Cantonment',
    skillCategory: 'Garden & Plant Care',
    specificSkill: 'Arid climate plant care, rose bush grafting & organic soil enrichment',
    experience: '12 years',
    baseRate: 449,
    rating: 4.90,
    completedJobs: 140,
    bio: 'Master of heat-tolerant greens, blooming flowering pots, and balcony upkeep.'
  },
  {
    id: 'pro_amd_senior_1',
    name: 'Kokilaben Bhatt',
    city: 'Ahmedabad',
    locality: 'Paldi & Naranpura',
    skillCategory: 'Senior Care & Assistance',
    specificSkill: 'Friendly companionship, temple visits assistance & medicine routines',
    experience: '6 years',
    baseRate: 449,
    rating: 4.97,
    completedJobs: 120,
    bio: 'Loving and respectful companion bringing comfort and cheer to elderly family members.'
  },

  // ==========================================
  // 8. PUNE (PNQ) - 18 Trades
  // ==========================================
  {
    id: 'pro_pnq_elec_1',
    name: 'Dnyaneshwar More',
    city: 'Pune',
    locality: 'Kothrud & Karve Nagar',
    skillCategory: 'Electrician & Wiring Repairs',
    specificSkill: 'Society wiring, inverter installations & earthing tests',
    experience: '8 years',
    baseRate: 299,
    rating: 4.95,
    completedJobs: 178,
    bio: 'Senior wireman with licensed government certification serving Kothrud.'
  },
  {
    id: 'pro_pnq_plumb_1',
    name: 'Nilesh Gokhale',
    city: 'Pune',
    locality: 'Viman Nagar & Kalyani Nagar',
    skillCategory: 'Plumbing & Drainage Fixing',
    specificSkill: 'Solar water heater plumbing & Jaguar tap repairs',
    experience: '7 years',
    baseRate: 349,
    rating: 4.91,
    completedJobs: 160,
    bio: 'East Pune plumbing specialist for solar lines, geysers, and flush tanks.'
  },
  {
    id: 'pro_pnq_clean_1',
    name: 'Vandana Kadam',
    city: 'Pune',
    locality: 'Baner & Aundh',
    skillCategory: 'Deep Home & Kitchen Cleaning',
    specificSkill: 'Balcony pressure wash & kitchen grease removal',
    experience: '6 years',
    baseRate: 699,
    rating: 4.89,
    completedJobs: 185,
    bio: 'Thorough Baner home cleaning service trusted by working professionals.'
  },
  {
    id: 'pro_pnq_carp_1',
    name: 'Suhas Kulkarni',
    city: 'Pune',
    locality: 'Kothrud & Deccan',
    skillCategory: 'Custom Carpentry & Woodwork',
    specificSkill: 'Custom study tables, wardrobe sliding channels & wooden repairs',
    experience: '9 years',
    baseRate: 499,
    rating: 4.92,
    completedJobs: 150,
    bio: 'Precise craftsman creating functional work-from-home furniture and cabinetry.'
  },
  {
    id: 'pro_pnq_handy_1',
    name: 'Rahul Shinde',
    city: 'Pune',
    locality: 'Wakad & Hinjawadi',
    skillCategory: 'Furniture Assembly & Handyman',
    specificSkill: 'Workstation setup, bookshelf assembly & curtain rods',
    experience: '5 years',
    baseRate: 399,
    rating: 4.93,
    completedJobs: 130,
    bio: 'Hinjawadi IT corridor favorite for rapid apartment setups and fixtures.'
  },
  {
    id: 'pro_pnq_appliance_1',
    name: 'Prashant Jagtap',
    city: 'Pune',
    locality: 'Hadapsar & Magarpatta',
    skillCategory: 'AC, Fridge & Appliance Repair',
    specificSkill: 'Split AC servicing, microwave magnetron & washing machine repair',
    experience: '7 years',
    baseRate: 449,
    rating: 4.93,
    completedJobs: 175,
    bio: 'Prompt diagnostic pro carrying genuine OEM parts for major brands.'
  },
  {
    id: 'pro_pnq_paint_1',
    name: 'Santosh Gaikwad',
    city: 'Pune',
    locality: 'Sinhagad Road & Dhayari',
    skillCategory: 'Wall Painting & Waterproofing',
    specificSkill: 'Monsoon terrace water sealing, exterior acrylic & interior royal paint',
    experience: '10 years',
    baseRate: 899,
    rating: 4.90,
    completedJobs: 130,
    bio: 'Effective monsoon waterproofing and flawless interior paint coats.'
  },
  {
    id: 'pro_pnq_tutor_1',
    name: 'Prof. Ketaki Joshi',
    city: 'Pune',
    locality: 'Deccan & Shivajinagar',
    skillCategory: 'Tutoring',
    specificSkill: 'ICSE & Maharashtra State Board Physics & Mathematics',
    experience: '7 years',
    baseRate: 800,
    rating: 5.0,
    completedJobs: 110,
    bio: 'M.Sc. Physics professor offering interactive conceptual coaching.'
  },
  {
    id: 'pro_pnq_spa_1',
    name: 'Swati Joshi',
    city: 'Pune',
    locality: 'Koregaon Park & Kalyani Nagar',
    skillCategory: 'Spa, Massage & Grooming',
    specificSkill: 'Therapeutic head massage, pedicures & skin facials',
    experience: '5 years',
    baseRate: 1199,
    rating: 5.0,
    completedJobs: 115,
    bio: 'Premium aesthetician bringing sterile, sealed salon kits right to your door.'
  },
  {
    id: 'pro_pnq_tech_1',
    name: 'Tanmay Deshpande',
    city: 'Pune',
    locality: 'Hinjawadi & Wakad',
    skillCategory: 'Laptop & Wi-Fi Tech Support',
    specificSkill: 'Dual-boot Linux/Win setups, mesh router configuration & thermal tuning',
    experience: '5 years',
    baseRate: 399,
    rating: 4.95,
    completedJobs: 140,
    bio: 'Doorstep tech specialist keeping software developers and WFH pros online.'
  },
  {
    id: 'pro_pnq_fit_1',
    name: 'Ajinkya Patil',
    city: 'Pune',
    locality: 'Baner & Balewadi',
    skillCategory: 'Yoga & Fitness Coaching',
    specificSkill: 'Strength conditioning, functional yoga & marathon training',
    experience: '6 years',
    baseRate: 799,
    rating: 4.96,
    completedJobs: 95,
    bio: 'Certified strength and mobility coach motivating sustainable wellness habits.'
  },
  {
    id: 'pro_pnq_auto_1',
    name: 'Ganesh Bhise',
    city: 'Pune',
    locality: 'Pimple Saudagar & Aundh',
    skillCategory: 'Car & Two-Wheeler Care',
    specificSkill: 'Doorstep pressure foam wash, dashboard polish & microfiber detailing',
    experience: '5 years',
    baseRate: 449,
    rating: 4.91,
    completedJobs: 150,
    bio: 'Equipped with mobile pressure equipment delivering showroom gloss.'
  },
  {
    id: 'pro_pnq_pest_1',
    name: 'Mahesh Thorat',
    city: 'Pune',
    locality: 'Wadgaon Sheri & Kharadi',
    skillCategory: 'Pest Control & Fumigation',
    specificSkill: 'Anti-termite drilling, herbal cockroach gel & mosquito misting',
    experience: '8 years',
    baseRate: 799,
    rating: 4.89,
    completedJobs: 165,
    bio: 'Environment-safe pest prevention for modern residential societies.'
  },
  {
    id: 'pro_pnq_org_1',
    name: 'Radhika Date',
    city: 'Pune',
    locality: 'Model Colony & Prabhat Road',
    skillCategory: 'Wardrobe & Home Organisation',
    specificSkill: 'Closet decluttering, wardrobe seasonal organization & modular kitchen storage',
    experience: '4 years',
    baseRate: 699,
    rating: 4.95,
    completedJobs: 80,
    bio: 'Professional organizer creating orderly, peaceful living environments.'
  },
  {
    id: 'pro_pnq_baby_1',
    name: 'Anita Kamble',
    city: 'Pune',
    locality: 'Kothrud & Bavdhan',
    skillCategory: 'Babysitting & Childcare',
    specificSkill: 'Infant care, creative story sessions & hygienic food prep',
    experience: '9 years',
    baseRate: 349,
    rating: 4.96,
    completedJobs: 185,
    bio: 'Compassionate, background-checked nanny trusted by hundreds of Pune families.'
  },
  {
    id: 'pro_pnq_pet_1',
    name: 'Tejas Sonawane',
    city: 'Pune',
    locality: 'Viman Nagar & Koregaon Park',
    skillCategory: 'Pet Care & Dog Walking',
    specificSkill: 'Park exercise walks, positive behavior reinforcement & pet sitting',
    experience: '4 years',
    baseRate: 349,
    rating: 4.93,
    completedJobs: 125,
    bio: 'Passionate dog lover offering safe, attentive, and joyful daily walks.'
  },
  {
    id: 'pro_pnq_garden_1',
    name: 'Babanrao Shinde',
    city: 'Pune',
    locality: 'Pashan & Baner',
    skillCategory: 'Garden & Plant Care',
    specificSkill: 'Terrace garden setups, medicinal herbal plants & flowering rose care',
    experience: '13 years',
    baseRate: 449,
    rating: 4.91,
    completedJobs: 160,
    bio: 'Experienced Pune gardener bringing flourishing beauty to balconies and yards.'
  },
  {
    id: 'pro_pnq_senior_1',
    name: 'Mangala Chitale',
    city: 'Pune',
    locality: 'Sadashiv Peth & Kothrud',
    skillCategory: 'Senior Care & Assistance',
    specificSkill: 'Elder companionship, evening walk assistance & health log maintenance',
    experience: '7 years',
    baseRate: 449,
    rating: 4.98,
    completedJobs: 140,
    bio: 'Warm and empathetic elder companion fostering comfort, dignity, and care.'
  }
];

// Attach realistic valid Indian mobile numbers to all verified specialists
PRE_ASSIGNED_WORKERS.forEach((w, idx) => {
  if (!w.phone) {
    let hash = 0;
    const str = w.id || w.name || String(idx);
    for (let i = 0; i < str.length; i++) {
      hash = ((hash << 5) - hash) + str.charCodeAt(i);
      hash |= 0;
    }
    const num = String(Math.abs(hash) % 90000000 + 10000000);
    w.phone = `98${num}`;
  }
});

module.exports = PRE_ASSIGNED_WORKERS;
